### ISSUE TITLE
Is the installation guide outdated?

### ISSUE THREAD

**Issue by tom10271** [erikdesjardins/webpack-rollup-loader#13]
Should it be `var rollupCommonjsPlugin = require('rollup-plugin-node-resolve');` but not `var rollupCommonjsPlugin = require('rollup-plugin-commonjs');`?

**Comment by erikdesjardins** [comment]
No, you shouldn't use `rollup-plugin-node-resolve`, since Webpack is used for module resolution.

In fact, `rollup-plugin-commonjs` should also be avoided if possible, it was just an example of a plugin. I'll make that more obvious.
